name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  precommit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 # use a pre-installed version of Python or PyPy on a GitHub-hosted runner
    - uses: pre-commit/action@v3.0.1 # run pre-commit hooks, see `.pre-commit-config.yaml` for configurations

  build:
    runs-on: ubuntu-latest
    needs:
    - precommit
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install hatch
    - name: Build package
      run: |
        hatch build

  lint:
    runs-on: ubuntu-latest
    needs:
    - precommit
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install hatch
    - name: Run lint
      run: |
        hatch run test:lint

  test:
    runs-on: ubuntu-latest
    needs:
    - precommit
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install hatch
    - name: Run tests
      run: |
        hatch run test:test
